apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: prometheus-stack
type: Opaque
stringData:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['cluster', 'alertname', 'severity']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - match:
          severity: critical
        receiver: 'null'
        group_wait: 5s
        group_interval: 2m
        repeat_interval: 5m
      - match:
          severity: warning
        receiver: 'null'
        group_interval: 10m
        repeat_interval: 2h

    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['cluster', 'alertname']

    receivers:
    - name: 'null'
