apiVersion: v1
kind: Secret
metadata:
    name: exportarr-api-keys
    namespace: prometheus-stack
type: Opaque
stringData:
    #ENC[AES256_GCM,data:YTT3mh9p4XGXMD0m1SgDP3izBIVSwDNgCG191Hv4O6KXnmC0Npu7mpMLW5a8yMbWbWe3JUDFrb6CE+Ni5OC3X/c=,iv:Ds7krPuIsJwbxUaQWQ510DmOCaYGCOBKmfP/UFdx58Y=,tag:r+gdJr82AEYnNy5+iNXW7Q==,type:comment]
    #ENC[AES256_GCM,data:oxlrcQDHrvLhsD5WwNAxWwWNpG9Sb5dtxxUzhnTqkxzHB+CUUqAHh64=,iv:nsD4H6kWT6NL2fAarXJL+08SIXSrozN38ClPHf54xX8=,tag:AkIIVnm27GKNnkI77mgUmQ==,type:comment]
    #ENC[AES256_GCM,data:ufeulHkoFNe7j7xKhT6XSfRIdpqfrJYFbS9Hwh7dNca12f2LE86GWZzmvyJlfZuadO4X37HTfkc=,iv:go2Kgj78pIxyEXHdybeH8iOOZfHzEAz4H6O75Aw9h7I=,tag:joAUo+MBNmhXOYb3Mm3cig==,type:comment]
    #ENC[AES256_GCM,data:xjQrieXrlefX5O52Ood0Chr2azYA+AVqiMxkkTgLsxGumq6fOxURd0jABgWxc6MGL+MdJ8/sfQE=,iv:EEHC+1Lzbnn9x9wQdSaRlEggybGIJ+4EIJaTcfbgt24=,tag:UXsvLNGp7q7sDAWmnwXjkw==,type:comment]
    #ENC[AES256_GCM,data:AuQjVs45TlzINNoZ/pE7j7dl5dXK8pF/ndou1sUryGoSeNwpReP245BKHDXtq0o=,iv:z7EYTkLkD50BKjam7m9vbpXk/3KTbijJYC7CyOXqdCo=,tag:hG4acpgjappeZwT+0/5g2w==,type:comment]
    #
    #ENC[AES256_GCM,data:3aBcXpn87YmO0FlFvFdHfuSwSHrUf70N0EZT5bd/qs4MI4feUlk34V3Z4AqXkfUE,iv:jkEr+tYVPD8s78BtNUutPYbqiXVQyZKBNEjfYm7c7r8=,tag:qsbRchDs/Kd/1CsUI0T9aw==,type:comment]
    #ENC[AES256_GCM,data:Ch84S4yKlNNHtUsh33IIde3VQT02gCZveLEOOXq0sfL3+CxA9a02,iv:s3TARp2C9gVUYkfRDFNsDFFBzXBY/8h0qDxcms+glQE=,tag:QQNCBmUKm+Ll3NwukMzLSQ==,type:comment]
    #ENC[AES256_GCM,data:x0iyixvnuN/37hQMh5ZtGQ8I9LN/gzBg2E1YoeqNegxrcQNc/juX607LQmpRWOqX7rB1+kBLDxxzvBwpIOohdlEiRTSkAek7,iv:KDBFV9V9MUjIz8kjsjTlUBlMBrPcwquQEuYEtzMTCgQ=,tag:XP0QyMLp31bj+o6XTfyAfg==,type:comment]
    radarr-api-key: ENC[AES256_GCM,data:DXeAxGNKqWBUbsSr2rJKYzLpUOkiAKv6NbJXmWEw1OY=,iv:KaXK5PHl2l18p+VN41fSkv0iuHOac/mWDH75TlIYMLI=,tag:LnQWvS/fLKOZx1eIp1XHNg==,type:str]
    sonarr-api-key: ENC[AES256_GCM,data:qzhk+g5uh4vD7M7EKhrtFh9aIQGxJs9NSmkrOxgeFTc=,iv:nrC8RVueBglOes3EqRrAw0I5kS21XUEdCrWtsmYvpXc=,tag:nIDPFWpYEULIMHL9UGp8Fw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132v2x3u5expx92pllzw2wy5es9c4emc4qs8cx4huh7eddd7ac4dqkscjph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeGh1OUJPZ1VLYjQ3Njhp
            QTA0TnI2Yjk1K0VOaW5hYnBvL2VwRUtJZWdvCjVpWEJ3S08wNitwRWJBNjFPK0xt
            UXFGalBaUW9QczZSRXpmVGpsazlHbFEKLS0tIHdZVjkrYzc5VGpkUHBlNHhiZmRj
            em85SmdwOTVHUDE1MXJneVIrNWpxTGMKSa5QiRun/WnbAjQnoQe029gSYgWUpBEL
            bmnLmYEmmaoNq/AUNzdTXWe/ulfnG/JX8VzijJre683Q2O/L2cPrcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T02:00:46Z"
    mac: ENC[AES256_GCM,data:iJgo6XR7DUYUnuFfKeeKfTcxxoKtZ9aaI7RYUbwTZJEP0t5zGPzCZ7hWsdOgYGUyMUm+Wxx6/5QtHzEn9+CkB4PaqrH8K/FbTL38hQnj23b5Y82HQTwPaRFMI9B3RgKEbrN2GUDmTxThOvdqUI2yaJ7OOc1RKqa+0p4J7V95t/Q=,iv:Ys9RpyoCQwqo5NfihmJi967L4ld7RX562W3AxnD58s0=,tag:sOCfI6LLJjWa5qU2R6gfGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
