apiVersion: v1
kind: Secret
metadata:
    name: exportarr-api-keys
    namespace: prometheus-stack
type: Opaque
stringData:
    #ENC[AES256_GCM,data:uBy0orhgz8w++v8l8ynDZ9sRZdq7oNGq0f0ijIYW7unwCdAnfMreBVVw2m0c5mbcv7kw0pBKDidWAGRtZqgbYtY=,iv:N7CV3J/x3HrxJrVTLdacyg/iuGwzIbcVaOkg0iyQmwY=,tag:buERb1VZACmBAWQNXAHawg==,type:comment]
    #ENC[AES256_GCM,data:ckbwcGp7bEPiSn82p1ZsOi7xrhPkhlIb3FzcZKp9WQXcl3fvqWdXthY=,iv:7T59AiCcGWWLE4YJ0NaiD+BkpqcydLrj+19+ToKEOWU=,tag:QE5pcNu9nI9uMO6lMIdwEQ==,type:comment]
    #ENC[AES256_GCM,data:R0+PJcYpvdfgDkpVnui0vUSrr7qrV0rKfOPo+kg+zaRj2wAcrMeVjEnXxLSyryqKcvXZT5IjmUU=,iv:UmdyiBfb2ZWp0V7T2ziAtrkWOu7XOjRgQ30nW3QBFSs=,tag:GGEr95m3hPpC0tnsxjr2Dw==,type:comment]
    #ENC[AES256_GCM,data:jXB6pVsHu6v1KQNte1XJx99AG0mxYX9rVsmQ98XuYhn08Biiy9bZGtQC042uFpwqXjBhgRjUoIw=,iv:/ht0pf483GCbzl6MIpnRY4FGav3YTG45P3GzpM58LUI=,tag:fjSHq+4pVUCrLwZ5wJ0I9g==,type:comment]
    #ENC[AES256_GCM,data:D6I8RUNofzg1c0W/qQtcaIT4KkZvwewSF+bGsezBCociu2qPo3zbIu8+ChKqi9o=,iv:+LA/pLiiaqaJR+3u1QgtWTq2qBynfGgcA5dav68T4d4=,tag:05Byorr1E28/VM2sHQxrhQ==,type:comment]
    #
    #ENC[AES256_GCM,data:oJTZGJ9JWD4aQkdgghha29i4XnxdkC29n8DEHWU3WaxbH2+dP/8SFkqvlkGHdefa,iv:JALanywezaDS6BCRf33eHai7kJaHmJrg0dXwrmsXa4A=,tag:DyE0/c4cfxiNN1d9pCKSGg==,type:comment]
    #ENC[AES256_GCM,data:pVsHWrmeQ/ev2a6FEILr47RyYlEza3Hcn7HsefJYv6E9mj51Byq0,iv:hFKIS5D0Knz6suzcxvDPXJp518wAu/zJjIfrJitMFUA=,tag:ketimLA50frCcL5fR75axA==,type:comment]
    #ENC[AES256_GCM,data:fTg0tSJsBxjCaegMOqeXG+EmY9ATgMHUKWI8YjnVlKGmtnksKFuw04zDX51zCKALINDkEJyUJNIwPaSuozTQPtx/E9BFRgvn,iv:MBxd2tafaUFJu0+AN75PBsiDkP43tF+8fpyaXRK1llo=,tag:IzhkIluBMfXlPkEq4Lqyhw==,type:comment]
    radarr-api-key: ENC[AES256_GCM,data:K1SuE1VOhkN1u8oEcfpcNMKXSoIAa4VEBm9iOxtNxvo=,iv:+mWmFxzHyxyzyW60r2uh6Q212TxuGTS01VS6erYu0L4=,tag:tc58xZ3qOgdVdyuWgfgsEQ==,type:str]
    sonarr-api-key: ENC[AES256_GCM,data:aTQB5rxwNSb0i+CHvyPQMYsx1S9SzgCALTDNYkPEy9U=,iv:kr3LggC+MIUr14aO7tGec/I8J1+T1VAYsD5MttgAOkY=,tag:gHojPayMlhlDU8dxAXhCjg==,type:str]
    jellyseerr-api-key: ENC[AES256_GCM,data:gR63uuTDPm8vFv6JtyuFcVeB4CavSC1GzlH9yAL1DUu+OjOdMErWJox72E6kPZt5Y1rlNcpuzaq9Z9Hje5eMCb+4WFc=,iv:T2xOW8GJW9cpBgGNdlrHqh9x27T0LFnP7HQymmlSxtM=,tag:7rWt96SCubeBAH0XiNu9bQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132v2x3u5expx92pllzw2wy5es9c4emc4qs8cx4huh7eddd7ac4dqkscjph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNlBDSy9LQW5RTy9VdmFr
            NHUweGxXL1d1Nkx1S2dUZkJ5T0ZjQzB2Tm5nCmFLNjBEMWcyQ0dtVkh5dlBsMzZx
            WHJjeHRxb2UwRVdibXF3TkRia1NLZ00KLS0tIEg5eGtjbXVlRlVtczlMRU1RRitP
            UlA1ZlgxSjRLa2J0NE5tdnJYTFpSQUUKfhQGLR69ZRm8t4GBodtn9zNaJDNxJ0mO
            MW09Bc79A++LB/lkskZSMADTR1I4NGf0d73GgmGgVwB/4E5T06GThQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T22:56:49Z"
    mac: ENC[AES256_GCM,data:fJzISpN7QgH4eTi/ZlmGCetccnPDmo9sBTz0E5CI9CHiBW7EK6yRa1ph78Qg9N8q1OPGlZAdS9J8NVTCZLuwSzfdahll4WL+UEbfWeRDDiWdczVJVbPuCTVRGCDksGTgdbmT2qPvN4xy5re6x2aykPEzrWOyJmBwWnky5YyBo6Q=,iv:J6KWDkcpdl44y4Dbnhqp6eNKyi2GV1kifG1mIjH69p4=,tag:D8fyMSVHu1i3dMZp4JObNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
