apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus-stack

resources:
  - ns.yaml
  - alertmanager-config.yaml
  - custom-servicemonitors.yaml
  - custom-alerts.yaml
  - prometheus-http-route.yaml
  - grafana-http-route.yaml
  - loki-http-route.yaml
  - alertmanager-http-route.yaml
  - exportarr-deployment.yaml
  - exportarr-secret.yaml
  - exportarr-servicemonitor.yaml
  - qbittorrent-exporter-secret.yaml
  - qbittorrent-exporter-deployment.yaml
  - media-alerts.yaml
  - media-dashboards-configmap.yaml

helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 81.5.0
  releaseName: kube-prometheus-stack
  namespace: prometheus-stack
  valuesFile: values.yaml
- name: loki
  repo: https://grafana-community.github.io/helm-charts
  version: 7.0.0
  releaseName: loki
  namespace: prometheus-stack
  valuesFile: loki-values.yaml
- name: k8s-monitoring
  repo: https://grafana.github.io/helm-charts
  version: 4.1.3
  releaseName: k8s-monitoring
  namespace: prometheus-stack
  valuesFile: k8s-monitoring-values.yaml
  includeCRDs: true
