{
 "title": "qBittorrent Dashboard",
 "description": "This is a Grafana dashboard for qBittorrent which uses Prometheus data source.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "All Time Downloaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "qbittorrent_global_alltime_downloaded_bytes"
    }
   ]
  },
  {
   "title": "All Time Uploaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "qbittorrent_global_alltime_uploaded_bytes"
    }
   ]
  },
  {
   "title": "Session Downloaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "qbittorrent_global_session_downloaded_bytes"
    }
   ]
  },
  {
   "title": "Session Uploaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "qbittorrent_global_session_uploaded_bytes"
    }
   ]
  },
  {
   "title": "Cumulative Download/Upload Speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "qbittorrent_global_download_speed_bytes",
     "legendFormat": "Download"
    },
    {
     "expr": "qbittorrent_global_upload_speed_bytes",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Global Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "targets": [
    { "expr": "qbittorrent_global_ratio" }
   ]
  },
  {
   "title": "Global Download Speed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "qbittorrent_global_download_speed_bytes"
    }
   ]
  },
  {
   "title": "Global Upload Speed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "qbittorrent_global_upload_speed_bytes"
    }
   ]
  },
  {
   "title": "qBittorrent Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "expr": "qbittorrent_app_version", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Torrents",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "qbittorrent_torrent_info" }
   ]
  },
  {
   "title": "Total Torrents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "qbittorrent_global_torrents" }
   ]
  },
  {
   "title": "Current Seeders",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(qbittorrent_torrent_seeders)"
    }
   ]
  },
  {
   "title": "Current Leechers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(qbittorrent_torrent_leechers)"
    }
   ]
  },
  {
   "title": "States",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "qbittorrent_torrent_states", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Amount Remaining Per Torrent",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "qbittorrent_torrent_amount_left_bytes",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Incomplete Torrent Progress",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "qbittorrent_torrent_progress < 1.0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Download Speed by Torrent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "qbittorrent_torrent_download_speed_bytes",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Upload Speed by Torrent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "qbittorrent_torrent_upload_speed_bytes",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}
{
 "title": "Radarr v3",
 "description": "This is a dashboard for Radarr v3 (exportarr does not work with Radarr v2). You will need to install exportarr (https://github.com/onedr0p/exportarr) in order to use this dashboard.\r\n\r\nBased on: https://grafana.com/grafana/dashboards/12530",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Movies Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "radrr_queue_total OR on() vector(0)",
     "legendFormat": "Queued"
    },
    { "expr": "radarr_history_total", "legendFormat": "Completed" }
   ]
  },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "radarr_movie_missing_total", "legendFormat": "Missing" },
    { "expr": "radarr_movie_monitored_total", "legendFormat": "Monitored" },
    { "expr": "radarr_movie_total", "legendFormat": "Total" }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Storage Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "radarr_movie_filesize_total" }
   ]
  },
  {
   "title": "Episode quality",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 8, "x": 3, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(radarr_movie_quality_total) by (quality))",
     "legendFormat": "{{ quality }}"
    }
   ]
  },
  {
   "title": "Storage Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "radarr_rootfolder_freespace_bytes",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}
{
 "title": "Sonarr v3",
 "description": "This is a dashboard for Sonarr v3 (exportarr does not work with Sonarr v2). You will need to install exportarr (https://github.com/onedr0p/exportarr) in order to use this dashboard.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Show Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarr_queue_total OR on() vector(0)",
     "legendFormat": "Queued"
    },
    { "expr": "sonarr_history_total", "legendFormat": "Completed" }
   ]
  },
  {
   "title": "Series",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sonarr_series_monitored_total", "legendFormat": "Monitored" },
    { "expr": "sonarr_series_total", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Seasons",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sonarr_season_monitored_total", "legendFormat": "Monitored" },
    { "expr": "sonarr_season_total", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Episodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarr_episode_downloaded_total",
     "legendFormat": "Downloaded"
    },
    { "expr": "sonarr_episode_total", "legendFormat": "Total" }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Storage Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sonarr_series_filesize_bytes" }
   ]
  },
  {
   "title": "Episode quality",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 8, "x": 3, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(sonarr_episode_quality_total) by (quality))",
     "legendFormat": "{{ quality }}"
    }
   ]
  },
  {
   "title": "Storage Available",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarr_rootfolder_freespace_bytes",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}