# Secret for qBittorrent credentials
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-exporter-credentials
    namespace: prometheus-stack
type: Opaque
stringData:
    #ENC[AES256_GCM,data:2w6260qmiwwWN9ZitCpWGPsNZjriJob1ssP2aEBgxgdnudiy7BM3Ik4DNLGrg34qlw50N44j6yyldzlusQRgO20F,iv:Q4uRf0HqlVGJzSBniJPW70K3DV5MmBcK/k9mO2QeKI8=,tag:QUi71F9gUE51Dx+o30UX5g==,type:comment]
    #ENC[AES256_GCM,data:hJOhcvM3mkttTnCZLDdxbb1qqpmsPP5SCK/rvEH7LtetyBbY,iv:Jj50zU33ab1iK3DaYQmNDom4QGWVHS1KLZGTAu530Us=,tag:ecS3ZG1rbqrHyBCih6ajFw==,type:comment]
    #ENC[AES256_GCM,data:Ri33UdVdW329yZyZWsK0HWzqBY+UqncmFrf93Gtp1ZeI7820N3x8vLqTT0lNbB314/XX7GU=,iv:nRuxsbaB0Dlzm7zdGWaSNSNAkywknc7kILVEev/tR2E=,tag:v7pffFMa8TmJIIWDH8E2BA==,type:comment]
    #ENC[AES256_GCM,data:oa2JY790rus42cHT/QVEUWYgzVEmXHYC6A3gC43dUg==,iv:BYb5HYPHiwRE2lhOu8/q3BqxXzYQj0JU9SAXORmiyiI=,tag:FQV+YC+CunraiZwmPB3vSg==,type:comment]
    #ENC[AES256_GCM,data:sjMy0iSTCGiwnXE4Thrl6UtsMPkfXL7MQpaWOlz30KZYVNP6u/nrY98c8prWkS0+34UIl5OF,iv:/8KiIfbPFCitIcZ4BviZaNQWbD7DmwHq2Dmob68axqU=,tag:L/44W+BLUHW84L6drA+1qw==,type:comment]
    #ENC[AES256_GCM,data:234YX4DZQZ4pFpr0dzsf/qzNL8rj8CQojU6NsyvDryLeTGQvo0m9gWa7nvCKZriAxsQHsGk0BPrQXHBquR4GJXO8Y+XDoKmM0Ji9Xw==,iv:z/DhEQl+XdtWsy1HYXXJjjGA8X8OtevfJ04wN6cZvy4=,tag:fDA+cgrVAtpjIcAdh1DRfw==,type:comment]
    username: ENC[AES256_GCM,data:dOWbUOw=,iv:AQ856hb0I4bwcK1JZAa8n0Dw4UdCIgiruS9ZOdx9naM=,tag:w8XqK1nyEeAhZB95i4YUZA==,type:str]
    password: ENC[AES256_GCM,data:V/jkGJuCaGlJ,iv:JQ0xeVRLPywc59UF/LQVfSTYA6w/d2/Zt56p9HoHf6M=,tag:Dg8g/Cv1DSQMTe26DyknhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132v2x3u5expx92pllzw2wy5es9c4emc4qs8cx4huh7eddd7ac4dqkscjph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaWxvMjBvTDlFTTF5T2tT
            ZWNWZXJidE95SVh6emp2dGlJMTJaSWVnTHhZCnNCMHdhTC9TdzNTK2RyUXVDcEdZ
            WXpEMTUxSWhtZUhMcXYwcmJxQ1hRMjgKLS0tIDdmMm1IZmdSVGZJMHZNeGhGckNS
            NEtnTGxFdUNHSHFERis5Q3VBcnRrRTgKUvx7LGMuezEO3vDeaNDjBtEpY/nQLz/D
            SPqG+WUHSUZooTfDQBpk4q+aHWGZyIHfB4KcbJDr2LwvE5MzoSzt1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T01:59:33Z"
    mac: ENC[AES256_GCM,data:utIqPXYq2qHb07CunhYgXZk+fBLd/YT94+ohSPc3HaL00gshp1Mp34uk4XBDOAKkejLvOUf4he2xJ2TxZ7k9T8oyIhmhhzWXcXUGyZPXW8lKPMUtp7PkwYKP0/8UZkU+ZBz3e/o/NuJ2Uh7kXJEfrmhQgfNbp/N2529nUthr5n0=,iv:p2TRLUrU+QI68ielpUI0BLdPcHyLoZS7EyqreoHk62A=,tag:inwopBfqmg21xKfLYhVAPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
