apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:/AZlrfkOnQuM+lIAtyA1RSc=,iv:xIVfHkU6Vg4b+uB6q69Tzy68stKiVC2x6j4+eccGrwI=,tag:bXiH9gnrWfrhLHty8pGP7Q==,type:str]
    client_secret: ENC[AES256_GCM,data:GrdHJPLbSXu6i1BgfS7ewvmCe9fiqq52O9FaFNb4eHqUcAo2u2cE8Y1u0LaSYQyfPjTNl4S8EBM2n2V6Lug9mw==,iv:cuJPHM85NdHsuMWFXT1/aTQ1laPU7pJz1g0Yn4zrw6k=,tag:e+hgykytQ2kmzFmKlfGFyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132v2x3u5expx92pllzw2wy5es9c4emc4qs8cx4huh7eddd7ac4dqkscjph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUExPaXZFWnpCOUZVUEZY
            WWJ5dk8wK1VXSUQ0Q3VBL3VLSFZ6Q3pPZVdjClpKVFpzTjlmemZPTmZQaUtQRHlI
            dW9rbTcxd1Job2RYUHI1R1RWd0ZpdEkKLS0tIGVRUWU4RjB3ZDY5T3MvOVZsZTBK
            dWlDM21EY1ZMaGFQWnhSemo3RkFqT1kKShBfqVsfuVQr0v2fEveBYH1ptkJOVple
            nZVQR/E0hGF8fshentxMmFYm2tj8Jwd7gDQioixEJPFBUboph4lc3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T04:09:03Z"
    mac: ENC[AES256_GCM,data:4jqm9pW79rzWXXqK6mW/ss5YV3pf5LeYuEyXZFCtTECe7OjenavmUaBPgpPCEMq1/ZIWmJBdhm3dNRjcNvE0ioLz0tey93xDBlBd+QxdXi03yvTSqrEtNWvl6gXtkDCmfazZP1BlRnu+XBhl+Riqc0Grb4+ot2FgCkgcIpId8lI=,iv:g/UWzkRxF8lNIa2hHEFtJn1uqbe3b2+cavJvMEk2g5M=,tag:xSQi6jzHelWqjFMj4eoMMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
