apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:YeTXcYd+rwR3mZJMXTCZSF8=,iv:Z4U1yHf8bF/JUmh8bF+wbcULgjiK1Ftl+eegPq27Uls=,tag:s9/fNHk04F1WDNu+dCSXGQ==,type:str]
    client_secret: ENC[AES256_GCM,data:Cypu4ZOaLwYQglB/LkE2s3wSIS8zrR3SW6GhKLdYeqTFucbAYW3ZVGuNkUPP5Ug0oS49qSQameyEP0e7XCz3Nw==,iv:0hMokXCxNTs165H1SnPHRU3AW/Yk20/7RiBl7LaEwjY=,tag:eZKNpuR7lPzwDpNiL0zajA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132v2x3u5expx92pllzw2wy5es9c4emc4qs8cx4huh7eddd7ac4dqkscjph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUExPaXZFWnpCOUZVUEZY
            WWJ5dk8wK1VXSUQ0Q3VBL3VLSFZ6Q3pPZVdjClpKVFpzTjlmemZPTmZQaUtQRHlI
            dW9rbTcxd1Job2RYUHI1R1RWd0ZpdEkKLS0tIGVRUWU4RjB3ZDY5T3MvOVZsZTBK
            dWlDM21EY1ZMaGFQWnhSemo3RkFqT1kKShBfqVsfuVQr0v2fEveBYH1ptkJOVple
            nZVQR/E0hGF8fshentxMmFYm2tj8Jwd7gDQioixEJPFBUboph4lc3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T03:02:03Z"
    mac: ENC[AES256_GCM,data:IbXwrrsR0g0UGXP7bdRbJBSH2yFff+1JL7IyoGORk9Xzfgy0TTRZJfY3nNwRfThJrMEYuAuJ+LthfQlgH5ApDd/DT38ZaF2JFmmq0QMN58vBg+ixKHy83OQ9COeUl9tP/SA50VJjy7YEpwenPoeCM3TrmD9akKu2e9sI0bZ/YRk=,iv:OVyphI4wlIEu4SjcMnA5FPewRkC0IZ17pZ6ngaKQ84c=,tag:IKUbO07CaYmvRAyZ6+HdXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
