oauth:
  clientId:
    valueFrom:
      secretKeyRef:
        name: operator-oauth
        key: client_id
  clientSecret:
    valueFrom:
      secretKeyRef:
        name: operator-oauth
        key: client_secret

operatorConfig:
  defaultTags:
    - tag:k8s
    - tag:homelab
  hostname: k8s-operator

apiServerProxyConfig:
  mode: "true"
