---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kopia-ui
  namespace: kopia
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Kopia"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "mdi-backup-restore"
    gethomepage.dev/href: "https://kopia.serverops.live"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=kopia-ui"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway-internal
      namespace: gateway
      sectionName: https
  hostnames:
    - "kopia.serverops.live"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: kopia-ui
          port: 80
          weight: 1
