apiVersion: v1
kind: Secret
metadata:
    name: kopia-ui-credentials
    namespace: kopia
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:R43Z,iv:CjuKAzwdyjD6PwillGlZbGqazonh2YKjj7Fqj3fim9A=,tag:Q3YkcXDjvYe5H3QnBOSKng==,type:str]
    password: ENC[AES256_GCM,data:l57FuCtA9etS,iv:Gb/jt+P6yWcpXWY4K/arKj0TXEPsRhQ8im6Se+VafdI=,tag:XsDmuLChm6ciKPcr39xPjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132v2x3u5expx92pllzw2wy5es9c4emc4qs8cx4huh7eddd7ac4dqkscjph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYazNtV2FOQ0MyMzNiTjZH
            S2RkOTFONTBESnR0OSt0M3c0OWgrc0R4a1VnCmgyUmd6U29zWmRpOXRWNjB6NjVx
            LzdSRWxWYzJSQ20ybTZacWJwNWVVOFkKLS0tIENzZ1FIdEJGMXBWblc2RmVZV1RL
            Nm5LTFY1RUhNVm1zclFBN3l1eWhRQU0KccogvKGg7u+uYqKu9+YU+8ynraJNx41k
            1b75xGZ10yliFEGPR//l05onPZr098rus0S3eVVs7DTGRl2G2+rYZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:02:05Z"
    mac: ENC[AES256_GCM,data:MthxwFnM6vgfUiJfHQeC/RM9QTa6lEH/QCkbiusfzV+MaoWWef2oxI6t9Mwfi7YvIfbJZg2obdPk31a8KJXs0uavGQjqhvU4D7B+oPjdML1T1YbhtuzzDy7lsZA27MfIH5TajkLWZ6MuZOP2SxJY8PrOYUhSLl3oG4sKx8r+YNM=,iv:BFFvQ02srsg3G3S3iXea4zdrGfx1UeO5BJ4wdMyrjYg=,tag:2XSqn5DJBTfQzdEsmbJtdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
