apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-media-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.5.10
    path: /mnt/pool/share
  mountOptions:
    - nfsvers=3
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-media
  namespace: bazarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: bazarr-media-pv
  storageClassName: ""
