apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:KwIk/SKZeEPXJVtyHJoJDBd7pyyyNjbzGn7Wt8Pn1b6x/XOw0oAxNQ==,iv:dT+SumFqzUp02Z4bBOOMorGH+q+rampN2hrA4mqWPyw=,tag:+8R9342v2k0547veXPADGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132v2x3u5expx92pllzw2wy5es9c4emc4qs8cx4huh7eddd7ac4dqkscjph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMVRTQ3plRFFwKzBOa1ZX
            N0lTd0lzVE1WOWxJMUZ1YjNVaUs1RTFwZ2tFClZoZkdXZEpuL0dOcGwrbXFZWmUr
            S3lNY0t3VktoVTBjZVptZWhqb1BDM28KLS0tIGZGNFgwS1RabVB6cEJMTllsZmlu
            aTNLRWR1dlBCWUFvZUhRcEVGSlErbk0KB8608qoZr3m9kTsREiUHEKzyFjHBgcFO
            MLPQDVfQn3q6T5cWi7hTjCaP3GLUt/s2XnR7BkqNu82Sak48l+SQyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T23:37:04Z"
    mac: ENC[AES256_GCM,data:OiPk0EZJnAwjwllknvH5MK7JftUuykX9oTb4cO5lt6+53Gnh3+iJ4VXq/S5h57vq6reMuNJlVTGruPFBs10kdliOsniaEHZJ+OjMe9lktG2eVGl8VHhCI6X5NsCrVZo5OSeLckRY6uY7yE4H9UQIbkgaOAGsWE/95WMj344ELPE=,iv:VjU2fUMYX+fEYoc6uLt2dkNu56DpJD/02AcxWLs8msQ=,tag:lL5HAnglpH3QsdePpTr3tQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
