apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-config
  namespace: nzbget
  labels:
    backup: "daily"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
