apiVersion: v1
kind: Secret
metadata:
    name: smb-credentials
    namespace: csi-driver-smb
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:L8sH,iv:CDFUdWXWRXtjyjJkE8hx+MPvUeOnPCBdodYQIela7S0=,tag:UI19mUUVJ4E8Qjx2hAI8tw==,type:str]
    password: ENC[AES256_GCM,data:vcG8ItgODq0+,iv:KkbO27KxyO2LkiqIR6rC3+xtBxnum6KWNFnUcBH5yZA=,tag:xYWTvhyJDJ7dhYDPCCK7WA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132v2x3u5expx92pllzw2wy5es9c4emc4qs8cx4huh7eddd7ac4dqkscjph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTDVCMkJrM3FmTjczL25N
            OGk4bVUvQWtWKytJSXVBOVo4UTJVRVBBYm1BCnJCbmNydUJNZk9GeTJWSk9wNWpP
            d0Q4bVB6UEFkT0tQRVh2eEtnRWc2UmMKLS0tIEhXWVN2d1pCWTRhS0tndFdwWU9l
            anRPa3VVb0tLN3d5Rm9IaU41dTNFSEEKAwV3BLCCRv+LwpkuQ3rFKN2ICsctJ7x/
            jEkeTtXxDcs1179c88udWwG0lde/nvOq3a1UAkztYH7mxqFfE/P2VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T06:05:13Z"
    mac: ENC[AES256_GCM,data:U7Yu4EjKoeVagkGTvlxxVZqPaGIJecLjsqsjppBB9hZSA/mEVbJEp6zpAfBrVbjUd69AM+0QDsuWpCQ/HkHVzCNJyrrpMiiYbPex8I5SlS2KmJ+gSXWXKgu6TtptiexOUzbqQziHCLkfYe4hlMI8YFOqI6yFNa5l6T+tuzdy1XY=,iv:vJUgQEjGaC8HLePI4El+lPsAyOl8qBMwQPx6NIyCst0=,tag:UDF0b4gECp3VVxu+sPQ2ug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
