apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres
  namespace: immich
  labels:
    backup: daily
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
