apiVersion: v1
kind: Secret
metadata:
    name: immich-env
    namespace: immich
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:ANsJRwA0Mg==,iv:dEw8f/F0688M64zzTKcTbDkutRpiPcaQscrPhgjSVPs=,tag:BxBPPmiWx2RlFqniHAPR2g==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:XxfOtAFXpgL12/h3mQ==,iv:x2/8PZms9L7us/FHZsDR8te6uj42ol5o4EIdlze9vOw=,tag:dAtPkShe1umkesYgqm+hag==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:GQn+rx5I,iv:zbvusK6SCzqMWe5syD9HMfHA72kr7JjI5K5A+DtWoRs=,tag:1P/o3lpVfbrEy/Ma7yy3jA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132v2x3u5expx92pllzw2wy5es9c4emc4qs8cx4huh7eddd7ac4dqkscjph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdEdEQjlVc0Jzcm9rc3ZU
            SmFYdVM4ME5odklPekJLV2pUQS9ydERneVNBCmh5ZHJrM05VN1JIeFVWcUVWNlBl
            enZYOWl2VVluOXNSNDFrRXBiL2RZOVkKLS0tIEpveEZxRDRZV0xxWFZ0YSsxcktD
            OURMSloxaVNZaFZrRk13bTVwVWhTRjAKeyLua6yLacrSqDKfNKAhCEIYr11Qmw2/
            tfZMSaFSjei7N073t/6Xz2xm1/83FffCd0R5fZ11F01PrgQLsIyo6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T15:10:03Z"
    mac: ENC[AES256_GCM,data:ku8OeS15EKOv61Zy/2J1uzTu6Pqx/kYM4QNKfMtPwE7ybuvkktIrE+42KlY/+74Cst9tRwfprK8D4FCq5VYBuPiUMNbJJRVfTsWt0QHA9KGluw3RinjfCyOCFRAoHWrhzc/9DXvzwL3AYSn3uGfaNIp5Hq/IrQO2SP7wlrwF9WM=,iv:eUqSWhsHvkPwGj/8h9H0eYdZ822FQsd5lZsl/ddq8Io=,tag:Nbk2fHIID1oueBYTZb+PpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
