apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbt-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.5.10
    path: /mnt/pool/share/qbt-config
  mountOptions:
    - nfsvers=4.1
    - hard
    - timeo=30
    - retrans=3
    - noresvport
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbt-config
  namespace: qbt
  labels:
    backup: "daily"
    backup-run-as-user: "1000"
    backup-run-as-group: "1000"
    backup-fs-group: "1000"
    backup-kopia-repository: "filesystem:///repository/qbt-config"
    backup-kopia-fs-path: "/repository/qbt-config"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: qbt-config-pv
  storageClassName: ""
