apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbt-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.5.10
    path: /mnt/pool/share/qbt-config
  mountOptions:
    - nfsvers=3
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbt-config
  namespace: qbt
  labels:
    backup: "daily"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: qbt-config-pv
  storageClassName: ""
