apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbt-torrents-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.5.10
    path: /mnt/pool/share/torrents
  mountOptions:
    - nfsvers=3
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbt-torrents
  namespace: qbt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: qbt-torrents-pv
  storageClassName: ""
