apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless
resources:
  - ns.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - data-pvc.yaml
  - media-pvc.yaml
  - export-pvc.yaml
  - consume-pvc.yaml
  - postgres.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - http-route-redirect.yaml
