apiVersion: v1
kind: Secret
metadata:
    name: paperless-env
    namespace: paperless
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:X2PIu6n2Ui4=,iv:fYSVAsXhDrzwNy1D5PF0UHC5KFpRivMzQ3e/kN5JjB4=,tag:Qr8UrwyCXjayCpfz7BW3Ig==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:fHjmHf0=,iv:ulhSzVi5gGNQ+a7L32qGv3DbOwbKIYTrg7w3Ta9n3oQ=,tag:lbfdenADd/mSt1QmFi6/Sg==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:L7QM6bmOzHo=,iv:w/snooYyh62Jb1xT+t72RION5nReUiINthAj6Hr0D+0=,tag:YBrvh7izqg3+mpwsL9IfFg==,type:str]
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:zPEPDzfgSTRm,iv:ueEULZxPX2NLGhC1K9NxMTMBtSafbOWW2p05MHyGC1Q=,tag:1PKC8j5RZXxICzcxB6oUEg==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:SqqnC9uOkoM=,iv:5tGalHEnTYgbrEWjAEPhYmKSVAMSdqJwXJsr44jUq7s=,tag:wykbF/SxwH8hZ/i9lXoOyw==,type:str]
    PAPERLESS_DBNAME: ENC[AES256_GCM,data:toyrVg16XKuy,iv:XhtJmepHkmymVn/F+yZjDq9rSmxfBcF+8xlCinb5R+o=,tag:W07lppT3hnlZRrYCmLCUFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132v2x3u5expx92pllzw2wy5es9c4emc4qs8cx4huh7eddd7ac4dqkscjph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dHNMTytVVmxsS29iQ2Jr
            dXBJYktTWjgwZStnekZqRE8yWHU3bWc4Vm53CjU1aUY1MTErT09IaHQxSDdZWS9D
            TmUyVi9VSSt6QlVJbVB6bHFIVHV0dEEKLS0tIHl3WmF4UVl1bU02Tng3NUk1dkZQ
            QWYzSzAwMDJyZ2ZsREpWc1VNb1NCMmsKgNT9HBTmPVfAbWZmFq5lWKpEE8S/2t6T
            ZqFkwVk8dpKwW46QCdByBrI0TwOMsRnrTjh2GnK5phq8Wmwj8WYeyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T16:55:37Z"
    mac: ENC[AES256_GCM,data:ry3bQYLmxNZGbNV+Ny54d3HhICOaTJiLFDQqQ5L6jx5HzewMW2/QHx6GOVtjUHaDn2wpO7jVk8QDis1B75Qv9MONUohlrt8X0TqLTdjIz8Pt/Rj5iNLvXl4k8qdlB941G2LRsCekH9bMuZpWM4mPyJB3Y9mMyhh5c3HE3lXgIPs=,iv:0oEJetfliqMiqBuxbPSgM+RPQ3yGZoPNKCloR/+uxms=,tag:RTKjj+8TLm8qnBKkGT3QBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
