apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reactive-resume
resources:
  - ns.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - data-pvc.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
