apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reactive-resume-postgres
  namespace: reactive-resume
  labels:
    backup: daily
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
