apiVersion: v1
kind: Secret
metadata:
    name: reactive-resume-env
    namespace: reactive-resume
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:QGoVFrb7tVQ=,iv:jbb7XDrYfQPYb8/ATu4gFJSQZkFLX5v+ZwCo5U3wUzk=,tag:ZptWOeQeZlHrrhW+Qd0xJw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:bXU6fWHNOoADQFciTWP/SGofHp3ov9bFuEKGm1rfboU=,iv:kgqckIXcl17t41yEoCqKZ/rtxzzQFdT1dgr2V2Q0PRQ=,tag:hZiFJSgiSNiiF2Z2fmdHkg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:HP/hlXONRqE=,iv:Oa7uN5ws4Y316JQYw12l20p8d5sl1XKFrKJHuH+1qqs=,tag:4fACyTHTHR3/dMCgq8q4oQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:eDJS+m5W0TwZ5hLYSFCJg2QEZP30RGXPlGwps5QKreQQtkCMT1tkXSe2dyZKiN27z1ImOpLYGKk3gtSOTtuBWvXEfr1NViGrpck1/Ex2sEV4lgeP2iSKRfwgzvpf,iv:xlF9Z4BBbPFPGi+egOyyKDJgWh5PNov23qIYj5Xj0Bg=,tag:IoWaA58GgfSIgP/d/So9JA==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:C0rDptNIfctVrhUqKCjnVxmVdfXgwofK2kN6OtiT+Qd6YXjC/A4AWJ+LLNtwFHFCUCHIrdy/Cz+m3w15M7MLdw==,iv:4t7ECZqFpYsHRHyEDVazCcbkeNBN4+xI4f7wKzlNe1M=,tag:IBB4l8xPRhcNmLN6IMxXcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132v2x3u5expx92pllzw2wy5es9c4emc4qs8cx4huh7eddd7ac4dqkscjph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcEZYR1dpa0NyaGQxbmFW
            bUZGbVg1UHAwZHZDdEZsRUhUZjlDaGlpNVVBCmczSzMrRlNBVjlCQ0svYkFZN1d1
            VEJKZi9yRCtUV0VlSUM2Z2ZGRTZrVGsKLS0tIFlHVW9VaklpcGs4TG1La1JRek9G
            bTY4VWxMSGVUdkdEOFR2OWFqVUlBWW8Kio/5GuboB0Uf1UHYRww7U3vbf76N4Qzd
            jnN3tUtESQtjpLH/jIhHggbjbT8YecGSgc2qqFXpG4uczv800X7b9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T01:29:17Z"
    mac: ENC[AES256_GCM,data:RQXaZPTp+ODoxrm0NeZ1Kw41Xxzl7gIMEQiQTXyEv+x0dqzgYnbwCzOQMKAw/JK7W/v3dJoG8CqFk6ChNXA8tJ9CyEuin2axoLnjyH1cKRT8XWehfpfr0OdXWG9a81zjvKsKP1kxaFhYKZzNF/UNfHSzd+5RmA0HSvEUZ1rzLW0=,iv:vwWh6CljWBdhd7iWqasDuLznXsLKxd6lvJstbwyokds=,tag:24uL7e5bst9X5JKdpWseZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
