apiVersion: v1
kind: Secret
metadata:
    name: sops-age-key
    namespace: argocd
type: Opaque
stringData:
    keys.txt: ENC[AES256_GCM,data:11YycKL9jwqKVxiX5NyREnf3h5vBi45MyNKMggwNIBeQdzfd0k8830nmJeQdOZb9LF82hsp3BCyOZUwfy5P3C99wAJtpLExvLP0tFUUDe7YzFqcSwBYWka1uyH8mOCUUChrUjeneWCKnFabRN/ZKnDDBvDuIrkfI4pcXTV721x016wLjLo2TSmZRVHr6bhQukjt7KHUoOHzCnAqLbIx3+QaB4xm8aDiRRFDnSKV1K8MCGDKC+54MmGRpNVv1,iv:0UZ5UFMIn335mgQHpIvehQa325VbLHNSINrdwE6Hy6s=,tag:OqfrjqUrMGE4SswcvFwvXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132v2x3u5expx92pllzw2wy5es9c4emc4qs8cx4huh7eddd7ac4dqkscjph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2c21ZcUVpZlgvOVY4SUNS
            SjlPeHcxRlZLSlVOZCtneVN5OGNtZUJqM0dzCmxLZzYzRlM0QnM3aUF3djBlbkNa
            SUlIWHMzWnRwSnAwVDd4dmFoOXFEWEEKLS0tIGllOXNiL2p3ZG1yZitxVGpWQ05F
            YmRaUkJxeVpjclJ3cUJPejBONHFaZHcKVmIgzLDv01MyeJ/pD14fR3z5HSpyhlRq
            QYgMvFp3h3DHb2/H5qGeY4NetuZVI0cjqCKopAzYOxX+XTv4uuUCUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T23:19:10Z"
    mac: ENC[AES256_GCM,data:K0YtiwHB331tCvHcHjsSNKo69wnm5qa1SspP3zOwVnsSpcIZzkWNJFhm+HAgO93Rx8uiuN8RA5LzgbO5MGmH7QmkA9imnWVASpUijyBRB/hgjw+POyfy8gNEWFeiAB5RBmHeZvl6zy0d9GCFTdurghao3gyFnSJAgn8ZsApt510=,iv:SUSdZ2dYrFRjAoBO5Bxw8jVAe2n3mbKUFJUNWzFv/Is=,tag:yN23lggQ8SRuX3YUSEZPTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
