apiVersion: v1
kind: Secret
metadata:
    name: kopia-repository
    namespace: jellyfin
type: Opaque
stringData:
    repository: ENC[AES256_GCM,data:1GS81b8VF4IBjP7XjKGvunXpT1iH+V5TtWxEaF+HqtI=,iv:SgclXSFUX38sF1bfOA8sM/VyBn6ePZJN0EHyQ9pFrfQ=,tag:NU3DLHyp3D7mGPMjMkxoHQ==,type:str]
    password: ENC[AES256_GCM,data:01eUlt4+J10K,iv:5wjAc8urkymyIyONFgd9foqJqsntVcmz/110XvU31wE=,tag:1P0r2t08BUjhFkvYlEbzww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132v2x3u5expx92pllzw2wy5es9c4emc4qs8cx4huh7eddd7ac4dqkscjph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZTNwcTZjcFgxU2VUcXJ1
            TjVmZXZJZllYRzB4NVdHTTFoWUtRalo1cVZzClYySHVSVDUyd2Vub2hMdkxDN2Jk
            eFFhYXNwdDVIbjVUZGI0eUlLRVlCaGsKLS0tIDVmMkpaQXRIMzF1SHVZT3VDL0sv
            RlFnTFFxcnMzTWV3QzduN09NMVJEdFUKkgNNAUdEVDDZkoPK6dBZiqsCYN+AXqEg
            qvk66XV/dArPc1UbEy9nUvktAv8GTS5CO5mJoDaKO71xFkic56dzDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T16:34:37Z"
    mac: ENC[AES256_GCM,data:xBPC4Ab2+iadzNIrlQGukY+W7UzlLzrv2Secy7CF0z7mrtWxi5aqOqfc5UwJnvWXCfbvWeaEYjCPDjJE9EUh88V8Uc5V1WSt3sAfh6qQvaSpCVvAaPgicqCG24TtkLKGlbWm1+eCCwnO23ReyCe48YBKem2F1n7REzeChRT+/k0=,iv:3J/A5iqs6ZDyuHmtMnMvIu/doLl5UEkkdhRgQrHLfrg=,tag:dXEa9jf3T2AkydiLowX2vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
