apiVersion: v1
kind: Secret
metadata:
    name: kopia-repository
    namespace: jellyfin
type: Opaque
stringData:
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:cKuv7lI=,iv:WNdgA98NdcddneSHPTqo1o8xAz/05H9G0ZlIgIs0oHw=,tag:ppKbOBIMmM60u93eWYg4EQ==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:AqLyaX/FUUXg,iv:/H3QAkOBQYygNnagmw30UmabPPsCt2Ak0Spehn+wWhg=,tag:7r1ipKphWN1M2SijxuqNRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132v2x3u5expx92pllzw2wy5es9c4emc4qs8cx4huh7eddd7ac4dqkscjph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbDlka003RVdzaHc4dERN
            ekpmN1hLbUQwdC8zZ0g4TnBtalVqSGk4QkFBCmk5ZnNNRDhnRWpRcFhMRjg0WjhB
            eGE4NFlqbVZnbG1ycVNKbjhDNXZTV0kKLS0tIDdaNzR1Y3R5d2JRczdxRTZTNzBw
            eGNWL3ova0JWdmoyb3RDUHRzN0Q5OWMKV6ajA6oRxsK/CBhMSoQqEA8zjwLN/gCX
            vXPw6LIgSt4GaaAmPfIpt1kpHc3jRDJmQ6ZOiTpfiou1umU7asg8YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T17:00:52Z"
    mac: ENC[AES256_GCM,data:LgKs9M6HRH7hYlxqmkcJWhINs0vSdX1wZO3Pz2aRuVSnO1Lg7py9eLu8G6FcQKbfQCg9d0sYnRoBSPe8nB64ugF6FtvjFRnSazJvjGLtFSbrw7k2L0ErOwHXwe2PxiuOS8Ttfv9TrdZxJbi+dmw1fdWyftsBPw3mJSCEysvjT1s=,iv:hrLY0DamFlvwHdgtVZd3zEsA142HC/waL/6rUj2+3zE=,tag:vecUA5Eoz23UXDu58J636g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
