apiVersion: v1
kind: Secret
metadata:
    name: kopia-repository
    namespace: jellyfin
type: Opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:zq5USqZefTxZ,iv:Rk2Dfb6A38P0ZoL2yFo3GLDorpRXrELipvasLFfqOKo=,tag:2B4WfbQc9J/fjv3MqvB7MQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132v2x3u5expx92pllzw2wy5es9c4emc4qs8cx4huh7eddd7ac4dqkscjph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBenBkT1NNZ0NZWUlWbFJr
            TTdxZisyVm5zSFMxSysycDRtYXk1cEowcFZRCitLZVJzV3hlczdIOTluUUlZQWh3
            VDExakV2c21PNm9ZR3ZlQk02UXIyUjgKLS0tIGp4eGZ3bmlyUzdMekUvQThMaHFj
            Z0drWGRnalZZd3RtbVZPRU01cG80NEUKvoAwbK27fQlBmIFXk+OwVEz9UwQUlOGU
            XbMMlt+DuSdLtX1N9iVW1Mu4ZfoLNmTPdmAbmsOAm034l7Qj7OQwxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T17:06:23Z"
    mac: ENC[AES256_GCM,data:4pgwhaBzGZOXkP6cy8ygQqINZooujtaCXmKonkN9o9zoaftZA1P5F4PSEt7ApsCnKVktZOCbRW8NkRA5Kuae2dYZZgimdK5MC6pWveljsV2wMwiAF+uTxOJssaGYHzV53C3kCmOkLPQDUWVq1iyulnPH3A45PL25uz/hYSGm9Tw=,iv:TVozc0ddekmeP2vo99apFLYDqkzh0iY0VXxe6C7KMPk=,tag:xnR374qJn8G2pjT6s9q8lQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
