apiVersion: v1
kind: PersistentVolume
metadata:
  name: kopia-repository-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.5.10
    path: /mnt/pool/share/kopia-repository
  mountOptions:
    - nfsvers=3
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kopia-repository
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: kopia-repository-pv
  storageClassName: ""
