apiVersion: v1
kind: Secret
metadata:
    name: restic-repository
    namespace: jellyfin
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:JkS1D4ZK8RzgnOo=,iv:Hs19xyU7X1MjRE2fBrSp2NDvXxnWr+q+hjOOJhLRd6c=,tag:H6ObKccRJ61/+6AOmytQDg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:C8GxV4Ja5G36,iv:m/KPlyp0xGpCiLFLB71wpDDf4UNpWB/NlGP2KvtEU00=,tag:N2dzyqx4XFykLletuOm1xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132v2x3u5expx92pllzw2wy5es9c4emc4qs8cx4huh7eddd7ac4dqkscjph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnc25lWi8wcHlYc3VaZ05z
            TUtpb3ZsbEhaemNHajVpSVRyTFZRUXRGZEU4CjhEYVFydGJIWVVxalcxaHFaR2Np
            YklIOXNYMFpqUDZ2OCtXbDJSbG1LN2sKLS0tIFBtdjVmcTBYZ1NUbTFKQzU2TS9O
            ekdFQS9xTEI0YnBaUGxVVDFhZDgzeFUK1nrpVXBoUxcJw6Xon9QBa45Lmq8EcA72
            DAeSYFnGsKE50vkx0jU0KnTSe0nJxxJonOVdin6AFZ+KU3PNbw1e5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T18:09:49Z"
    mac: ENC[AES256_GCM,data:Y6P+ASQYN+2SBfwOfVTXbs3w+Bc0rQ4OsNyffsC6jeuvKcfM3h50gFc9dWeUp/1Cp7sinK7WWVNhzp6PxGKlsOj8NYLA6yLzBh7or0C5MJZ4CK7H/lKse7dH/zpmIrcdbwaIs7XUDJhlywkgjM+GoxoXHDMzJEut4u9F/t48lK4=,iv:FyYOREEC2G2rluQMDUPV+um2pqBw84zDGwaRYoXOmO8=,tag:teaphZxHYli8DYY7u2NoeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
