apiVersion: v1
kind: Secret
metadata:
    name: volsync-kopia-source
    namespace: volsync-system
type: Opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:K/zAZLu2/xPv,iv:9eXfXxBTwAkEuyZFgHRIRrJ7Nv/U2luBzylDUGGRfg0=,tag:LUOEP0r9NG2qM1NbeuHONg==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:blsKCNgznO3xIdHrJE31NtOqztOaZfWd,iv:Izjl4cHoPZGZ5Kg3XU3umOZET4+5YckCXiMHOEgZ0SQ=,tag:/OmcBSKEdibvSDVgwZ06bA==,type:str]
    KOPIA_FS_PATH: ENC[AES256_GCM,data:5YalIOsFc6sLSck=,iv:QrGeJo3FokgEfFIa0aPEgZbI068K72mu0ccBOjTXHcQ=,tag:8a37MY8NLtiqwrsGZvZTEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132v2x3u5expx92pllzw2wy5es9c4emc4qs8cx4huh7eddd7ac4dqkscjph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRnl5QW4wUjI1c0lPTEN2
            U0V3SFpmUXJSWEgwa2NyT29zejh0M3VsQ2pjCm92NThibkNiTGY5V0RyNmM2aVpo
            QllaeEdpS3dheXVuQy8vT2EvK0MybTAKLS0tICtRM21GU0xJcVRUT3FmY2R4SEVJ
            aEg4TG9MY2xjWGZDakhIckgrdG15c1UKBrQEGUQGXweQ74SqtnlCronbDaN8HO5y
            XROn+vpNkFKMtpBobtZcwq459Ibv4LM4n9CH1IgdkhFjCJ/OnL8kaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T16:03:45Z"
    mac: ENC[AES256_GCM,data:/fKfdxFgCokgBX5IiGYdGrgWM4gYIpYOj08qG8xDhM5Sjgd2I8o1N+5egvnAZGbJTVQ5+HEy5c4TEONNqnbjHz4BXblXN9U2apYvfCi1pggDeo55vaQB4YLhuO/jvJYa8Q+cvuMRlfW2kWuvQ676WrJH/h4jdP0LBrmaIkp8LEk=,iv:K8GALOO98U6F5tMx6nAQfFMzf97GEgqeD3k1w8lUiMg=,tag:JLvE7h9ShOndL4h2C8ZNNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
