apiVersion: v1
kind: Secret
metadata:
    name: pvc-plumber-kopia
    namespace: volsync-system
type: Opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:/meY/33LNv4V,iv:uApifOQcw8p+cnaXiR0wtVGvTAGCkNvSkus+35N50eU=,tag:Cs4oCX/5wynPaG+VsCwj0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132v2x3u5expx92pllzw2wy5es9c4emc4qs8cx4huh7eddd7ac4dqkscjph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNWFuNWdKa000NGxPbWl1
            NVJtWnR2K2UvaW5xWkxvM3JKSHE4RlpOSEFNCnEzc3oxbVNvZTdLd0c3U1Irck50
            T0dvWVZ2OWl2S01tR2N5UjQvMFhRRWcKLS0tIDRiVWtoeEg0YkczeGZEaEcxUEJ4
            aVdHQ3FJelIxK2laU1hWUy8vaVYzQmcKi05WO8B3oX2yjtapejEhnVFRK3ThWFm5
            X3VC3MwzavHp3fl5Cx2IJaJbIF9NwdnzQvyQzrIPX9KwgYbJsmMSdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T16:04:02Z"
    mac: ENC[AES256_GCM,data:x3sR35aNT6EZGXN5T1HcOUSBVmhpHjsZoLsf2jkxHs4PkP0yqorjT/m0RALV4qWQNQABtmjDuDYE1JMn8R7CeqdLPLV8UXTM9o3VXGoX7CoDZ0HcqKnZl/ondm9Tw4rx7Lt7wWcHBfw9WELZoEZ7nGl2sZFJqQkUYEm4fBgcvho=,iv:J97wbsnTdbWt6JimS2wGBUETs/bdKOwmSETmzNwm55c=,tag:zcqCywfV3g6X/FqAam7a5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
