apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: radarr
resources:
  - ns.yaml
  - config-pvc.yaml
  - media-pvc.yaml
  - http-route.yaml

helmCharts:
- name: radarr
  repo: https://charts.truecharts.org
  version: 10.0.14
  releaseName: radarr
  namespace: radarr
  valuesFile: values.yaml
