persistence:
  config:
    enabled: true
    existingClaim: radarr-config
    targetSelector:
      main:
        main:
          mountPath: /config
  media:
    enabled: true
    existingClaim: radarr-media
    targetSelector:
      main:
        main:
          - mountPath: /movies
            subPath: data/media/movies
          - mountPath: /data
            subPath: data

env:
  TZ: America/New_York
  PUID: "1000"
  PGID: "1000"

service:
  main:
    ports:
      main:
        port: 7878

ingress:
  main:
    enabled: false

# Disable metrics sidecar for simplicity
exportarr:
  enabled: false
