apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-data
  namespace: karakeep
  labels:
    backup: "daily"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
