apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: karakeep
resources:
  - ns.yaml
  - karakeep-pvc.yaml
  - meilisearch-pvc.yaml
  - secret.yaml
  - chrome-deployment.yaml
  - meilisearch-deployment.yaml
  - karakeep-deployment.yaml
  - services.yaml
  - http-route.yaml
