apiVersion: v1
kind: Secret
metadata:
    name: karakeep-env
    namespace: karakeep
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:ij92qC9ewT71M2YdEAo3kTCIqNKUOFD+cXpnMwf8QHB1BOSyac0H3VWtR7c=,iv:67mJ7ufIjZd1kGzkOWyJJWkdbz4DP0bQOVGeA9JG4NQ=,tag:w1rNLaMOn7AyVl4iZlPNgg==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:uxC1yY0XWvYYkxyLiY12wL+egluVQkd0medOxzHF5+rbAAv5qrA0aGpZlWg=,iv:Ad9MUgep5UNrVUjh8hfYhRASMzRKniOwmbS+N9LFhB8=,tag:zx7CuXBZjm2iZuNpK//Qwg==,type:str]
    NEXTAUTH_URL: ENC[AES256_GCM,data:iwjvepdiIHoJKMaZT25SXTTl0Mr5v7E71QfC,iv:Fmc8MADs4GWKGQj+arzps6bmTDcRP9GagWs/rw5WwGQ=,tag:j4tcspgWOf3UxIApZp9ojw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132v2x3u5expx92pllzw2wy5es9c4emc4qs8cx4huh7eddd7ac4dqkscjph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMUE3NE41bmMyaFp4ajZS
            cWpwVFV2L2RnaU52QVFxVkMvL2o2RDBjdm4wCk1NZll6Wk84MlFWK0s5YjBTWDJN
            cmRnNWVwUytOeFROTUVNbGZqVkRjamsKLS0tIGd2R2w5cXFmVzk2RVBsbHZuWGJj
            SXFHQ3hMVGdpaEdUbXFkYVRFQ2ordU0K2gOzZusgTI4oLuqDkXdYv1qL39nhmtNY
            SmpfF9B3F5OXjyYdqZwM6OOzkt7jBo9ralRt31ziDvS3JaTsGr7XcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T03:41:32Z"
    mac: ENC[AES256_GCM,data:fbzMVlydAZLbhzYY1UijmCntV0nP4OQoMqcw2V+uXYd5UPl/CvXNXkUcO8RqBT969uPAztp+g4nMq2DmIyVGjN2jYa59rmV+5bENLCkoih8KePIgzhdq44NEzCPV5eKVNK7HLgSDLNpgJqTfRkg+84FvMJ8r7MIne7VCgzKyikw=,iv:h8OroUVL2h0irF5FdCUhXZWWpUrWdp2+sWKycYXvGho=,tag:Rw7wNmzEJiJ/BMUgra3jHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
